/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/base64/decode': RouteRecordInfo<'/base64/decode', '/base64/decode', Record<never, never>, Record<never, never>>,
    '/base64/encode': RouteRecordInfo<'/base64/encode', '/base64/encode', Record<never, never>, Record<never, never>>,
    '/work-logs': RouteRecordInfo<'/work-logs', '/work-logs', Record<never, never>, Record<never, never>>,
  }
}
